services:
  - type: web
    name: transpo-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_MODE
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: CORS_ORIGINS
        value: "https://bap-ex4jv8qge-bonitapurity-5527s-projects.vercel.app"
      - key: JWT_SECRET
        generateValue: true
